version: '3.8'
services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - type: bind
        source: ./banco.db
        target: /app/banco.db

#  postgres:
#    image: postgres
#    environment:
#      POSTGRES_USER: usuario
#      POSTGRES_PASSWORD: senha
#      POSTGRES_DB: nome_do_banco
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#volumes:
#  postgres_data: